### PR TITLE
Fixed a bug freezing the player when flashing during a dash

### PR DESCRIPTION
**Pull request by HarmfulBreeze**
Needs [#528 in GameServer](https://github.com/LeagueSandbox/GameServer/pull/528) to be merged for it to work.

### CODE REVIEW

**Review by MythicManiac — APPROVED** [review]
Looks good, just need to get that GameServer PR merged first. Nice work.

**Comment by FurkanS1821** [comment]
In my opinion, adding this code into `TeleportTo` method is better than adding this to every blink ability's script. But just saying.

**Comment by HarmfulBreeze** [comment]
The thing is I don't see it being problematic outside of Flash as I don't see any champion that has both a dash and a spell that would use ``TeleportTo``.

**Comment by FurkanS1821** [comment]
Knockbacks == dash
So, think about an ezreal being ulted moment before tristana ult hits him. He will be teleported to where he clicked and knockback will stop, but the stun will persist full time.

**Comment by HarmfulBreeze** [comment]
Okay I get your point. I'll add it to the ``TeleportTo`` method. Thanks

**Comment by MythicManiac** [comment]
Closing in favour of https://github.com/LeagueSandbox/GameServer/pull/531

**Pull request closed without merging**
