### PR TITLE
Scripts changes for packets refactoring

### PR DESCRIPTION
**Pull request by horato**
Implements breaking changes introduced in https://github.com/LeagueSandbox/GameServer/pull/643

### CODE REVIEW

**Comment by MythicManiac** [comment]
What are these?
image

**Comment by horato** [comment]
That's good question. I'd say VS2017 is trolling. Will remove it.

**Comment by horato** [comment]
done

**Comment by MythicManiac** [comment]
One more question, why do we need to reference the `GameServerCore` _and_ `GameServerLib` solutions? Are both really required?

To me this seems like something that probably would require abstraction or re-organization if true, but I'm open for dicussion.

**Comment by danil179** [comment]
The ```GameServerCore``` is the API (should rename it to GameServerAPI probably), but currently also handles packet defintions that we need to move to sort of PacketManger project, the API should give the scripts full platform without exposing implementation to break the server, and to give script developers easy platform to develop.

the ```GameServerLib``` is the implementation of that API+some other things.

the packets should be connected through bridge (that should handle the basic mechanics that we don't want to customize about packets, like blowfish encryption etc), s.t when in Lib some event happens it triggers part in the bridge (could be implemented with chaining API or events, the bridge will add some packets sending on some events and invoke some on recieving)

**Review by MatthewFrench — APPROVED** [review]
Looks great!

**Comment by horato** [comment]
Current scripts implementation uses internal server classes, that's why it references Lib. I didn't change the current implementation. 
Core should be the only one referenced.

**Pull request merged**
